version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  test-pypi:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements_ci.txt
      - run:
          command: |
            echo -e "[testpypi]" > ~/.pypirc
            echo -e "username = conductor" >> ~/.pypirc
            echo -e "password = $TEST_PYPI_PASSWORD" >> ~/.pypirc
          name: Create pypi credentials
      - run:
          command: |
            python setup.py clean --all
            python setup.py  bdist_wheel 
          name: Create packages
      - run:
          command: |
            twine upload  -r testpypi  dist/*
          name: Upload to testpypi

  release-pypi:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements_ci.txt
      - run:
          command: tox
          name: Tox tests
      - run:
          command: |
            echo -e "[pypi]" > ~/.pypirc
            echo -e "username = conductor" >> ~/.pypirc
            echo -e "password = $PROD_PYPI_PASSWORD" >> ~/.pypirc
          name: Create pypi credentials
      - run:
          command: |
            python setup.py clean --all
            python setup.py  bdist_wheel
          name: Create packages
      - run:
          command: |
            twine upload dist/*
          name: Upload to pypi
      - add_ssh_keys:
          fingerprints:
            - "a5:8b:19:87:d5:0b:34:60:3b:e2:1f:93:a5:c6:f7:94"
      - run:
          command: |
            version=$(cat VERSION)
            git tag -a -m "Release tag:${version}" ${version}
            git push origin ${version}
          name: Push a release tag

workflows:
  main:
    jobs:
      - test-pypi:
          context:
            - skulk-context
          filters:
            branches:
              ignore: master
      - release-pypi:
          context:
            - skulk-context
          filters:
            branches:
              only: master
