version: 2.1


orbs:
  python: circleci/python@1.3.2

jobs:
  test-pypi:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: tox
          name: Tox
      - run:
          command: |
            echo -e "[testpypi]" >> ~/.pypirc
            echo -e "username = conductor" >> ~/.pypirc
            echo -e "password = $TEST_PYPI_PASSWORD" >> ~/.pypirc
          name: Init .pypirc
      - run:
          command: |
            python3 setup.py sdist bdist_wheel
          name: Create packages
      - run:
          command: |
            twine upload  -r testpypi  dist/*
          name: Upload to testpypi

workflows:
  main:
    jobs:
      - test-pypi